export { type ChildLaunchProfile, verifierChildProfile } from './child-profile.ts';
export {
  appendWorkerStderrTail,
  emptyWorkerStderrTail,
  renderWorkerCompactionFailure,
  renderWorkerProtocolDiagnostic,
  WORKER_STDERR_TAIL_MAX_CHARS,
  type WorkerCompactionFailure,
  type WorkerDiagnosticCountAccuracy,
  type WorkerProtocolDiagnostic,
  type WorkerProtocolDiagnosticReason,
  type WorkerRpcRecordMetadata,
  type WorkerStderrTail,
  type WorkerTextCounts,
  workerCompactionFailure,
  workerProtocolDiagnostic,
} from './diagnostics.ts';
export { WorkerProcessError, WorkerRpcError } from './errors.ts';
export {
  type GuardedWorkerSupervisorShape,
  makeWorkerSupervisor,
  type WorkerCompactionCompletion,
  type WorkerCompactionReason,
  type WorkerQueueMode,
  type WorkerResolvedSendBehavior,
  type WorkerRuntimeSnapshot,
  type WorkerSendBehavior,
  type WorkerSendResult,
  type WorkerSessionStats,
  type WorkerSpawnInput,
  type WorkerStatus,
  WorkerSupervisor,
  type WorkerSupervisorError,
  type WorkerSupervisorEvent,
  type WorkerSupervisorOptions,
  type WorkerSupervisorShape,
  type WorkerThinkingLevel,
} from './supervisor.ts';
export {
  makeWorktreeBootstrap,
  renderWorktreeUpdateTerminalDiagnostic,
  WORKTREE_UPDATE_DIAGNOSTIC_TAIL_MAX_CHARS,
  WORKTREE_UPDATE_SCRIPT,
  WORKTREE_UPDATE_TIMEOUT_MS,
  WorktreeBootstrap,
  type WorktreeBootstrapOptions,
  type WorktreeBootstrapShape,
  WorktreeUpdateError,
  type WorktreeUpdateFailureReason,
  type WorktreeUpdateOutcome,
  type WorktreeUpdateOutput,
  worktreeUpdateFailureSummary,
} from './worktree-bootstrap.ts';
